<Project Sdk="Dalamud.NET.SDK/15.0.0">
	<PropertyGroup>
		<Authors>NahayaSakafuku</Authors>
		<Version>1.0.2.1</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<OutputPath>bin\$(Configuration)\</OutputPath>
		<NoWarn>CS1591</NoWarn>
		<EnableWindowsTargeting>true</EnableWindowsTargeting>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ECommons\ECommons\ECommons.csproj" />
	</ItemGroup>
</Project>
